# 플러그인 버전 (절대 수정하지 마세요!)
version: 5

# 플러그인 언어 (지원하는 언어 - ko, en)
language: ko

# 서버/클라이언트 포트 설정
# 이것은 플러그인의 네트워크 기능에 사용됩니다.
server-enable: false
server-port: 25000

client-enable: false
client-port: 20000
client-host: mindustry.kr

# realname를 켜면 플레이어가 닉네임을 변경하더라도 이전 닉네임으로 설정됩니다.
# 컬러닉 기능을 원하는 경우 이것을 활성화해야 합니다.
realname: true

# 컬러닉 갱신 시간설정. 1초 = 1000
colornick update interval: 1000

# 원자로 감지를 켜면 토륨 원자로가 과열되어 폭발 하기 직전일 때 즉시 블럭이 파괴됩니다.
detectreactor: true

# 빠른 자원소모 감지를 켜면 한 자원이 빠르게 소모가 되고 있을때, 그 자원을 사용하고 있는 플레이어의 명단을 띄워줍니다.
scanresource: true

# 이 기능을 켜면 각 플레이어의 블럭 설치/파괴에 대한 테러방지 기능이 작동합니다.
antigrief: false

# 경험치 값 설정.
# explimit를 켜면, 플레이어가 건설하려는 블록 요구 레벨이 되지 않을경우 건설 자체를 취소시킵니다.
# Base xp는 레벨 1에서 2로 오르는데 필요한 경험치 수치입니다.
# exponent는 다음 레벨로 올리기 위한 요구 경험치 배수입니다.
# levelupalarm 를 활성화 하면 일정레벨 이상에서 레벨이 오를때, 메세지로 띄워줍니다.
explimit: false
basexp: 500
exponent: 1.12f
levelupalarm: false
alarm-minimal-level: 20

# 밴 공유서버 설정
# 이 기능을 켜면, 다른 공용 서버와 밴 목록을 공유하게 됩니다.
banshare: false

# 신뢰가능한 밴 공유 IP 설정
# 예시 - 127.0.0.1,localhost,192.168.0.0
bantrust:

# 서버 요청 설정
# 이 기능을 켜면 서버 포트에서 서버 정보를 얻어올 수 있게 됩니다.
# 랭킹 사이트는 http://localhost:서버포트/rank/kr 으로 들어가면 됩니다.
query: false

# 이 기능을 켜면 VPN 서비스가 켜집니다.
antivpn: true

# 이 기능을 켜면 PvP 초반 러시 방지기능을 활성화 합니다. 시간 단위: 1초
enableantirush: true
antirushtime: 10.00

# 서버 로그 활성화 (이 기능을 켜면 많은 디스크 작업이 일어납니다!)
logging: false

# 플러그인 업데이트 확인 기능
update: true

# 데이터베이스 종류 설정 (기본값은 SQLite 입니다.)
# 예시 - mariadb://localhost:3306/DB이름
# 만약 MySQL/MariaDB 를 사용하고 싶다면, SQLite를 비활성화 하고 새 데이터베이스를 직접 만드셔야 합니다!
sqlite: true
dburl:
dbid:
dbpw:

# 로그인 기능 설정
# loginmethod 는 계정 등록방식 입니다. (password, email 방식이 가능함)
# validconnect 는 해당 플레이어가 서버 이미 있을경우 강퇴하는 기능입니다.
loginenable: true
loginmethod: password
validconnect: false

# 파파고 번역 API 키
# 이 키는 developers.naver.com 에서 유료로 얻을 수 있습니다.
clientId:
clientSecret:

# 이 기능을 켜면 오류 메세지가 저장되지 않고 즉시 콘솔로 출력됩니다.
debug: false

# 맵 자동저장 시간. 시간 단위는 1분입니다.
savetime: 10

# 빽섭할 맵 저장 슬롯
# 예시 - 만약 값을 1000으로 설정한다면, 빽섭할 맵의 파일명이 1000.msav 으로 저장됩니다.
slotnumber: 1000