# Config version (Don't touch this!)
version: 5

# Plugin language
language: en

# Server/client port settings
# This's used for the network function of the plugin.
server-enable: false
server-port: 25000

client-enable: false
client-port: 20000
client-host: mindustry.kr

# If turn on realname, even if the player changes the nickname, it will be set to the previous nickname.
# If you want colornick features, must enable this.
realname: true

# Color nickname update interval. 1sec = 1000
colornick update interval: 1000

# If turn on detectreactor, destory reactor when the thorium reactor is overheated.
detectreactor: true

# if turn on scanresource, show message a list of players who are using a resource when it is consuming a resource very quickly.
scanresource: true

# Experience value setting.
# When turn on explimit, cancels the construction itself if the player doesn't reach the level of the block they are trying to build.
# Base xp is required experience to level up from 1 to 2
# exponent is EXP multiplier required for the next level.
# When turn on levelupalarm, a message is displayed when the level rises above a certain level.
explimit: false
basexp: 500
exponent: 1.12f
levelupalarm: false

# Ban sharing server config
# If you enable this, your ban list will send to another public servers.
banshare: false

# Ban sharing trust list
# Example - 127.0.0.1,localhost,192.168.0.0
bantrust:

# Server query config
# If you enable this, You will be able to get server information from the server port.
# Ranking page address is http://localhost:server_port/rank
query: false

# Enable Anti-VPN service.
antivpn: true

# Enable Anti PvP early time rushing. Time unit: 1 second
enableantirush: true
antirushtime: 10.00

# Logging enable (This features may take heavy disk read/write work!)
logging: false

# update check enable
update: true

# Database type setting (Default is SQLite)
# Example - mariadb://localhost:3306/dbname
# If you want to use MySQL/MariaDB, You must disable sqlite and create a new database yourself.# dburl
sqlite: true
dburl:
dbid:
dbpw:

# Login features setting
loginenable: true

# Papago translate API Key
# The api key can be obtained from developers.naver.com.
clientId:
clientSecret:

# The error message is output immediately.
debug: false

# Map auto save time. Time unit: 1 minute
savetime: 10

# Rollback map save slot number.
# Example - if set value to 1000, rollback map name will renamed to 1000.msav
slotnumber: 1000;