# crafting
graphite-press: 5
multi-press: 15
silicon-smelter: 5
kiln: 8
plastanium-compressor: 20
phase-weaver: 35
alloy-smelter: 30
cryofluidmixer: 15
blast-mixer: 8
pyratite-mixer: 12
melter: 3
separator: 6
spore-press: 5
pulverizer: 2
coal-centrifuge: 3
incinerator: 2

# Sandbox
power-void: 0
power-source: 0
item-source: 0
item-void: 0
liquid-source: 0
message: 0

# Defence
scrap-wall: 0
scrap-wall-large: 0
scrap-wall-huge: 0
scrap-wall-gigantic: 0
thruster: 0
copper-wall: 1
copper-wall-large: 4
titanium-wall: 2
titanium-wall-large: 8
thorium-wall: 3
thorium-wall-large: 12
phase-wall: 4
phase-wall-large: 16
surge-wall: 5
surge-wall-large: 20
door: 2
door-large: 6
mender: 2
mend-projector: 10
overdrive-projector: 12
force-projector: 35
shock-mine: 5

# Distribution
conveyor: 1
titanium-conveyor: 2
armored-conveyor: 3
junction: 1
bridge-conveyor: 1
phase-conveyor: 5
sorter: 2
router: 1
distributor: 1
overflow-gate: 2
mass-driver: 15

# Liquid
mechanical-pump: 2
rotary-pump: 8
thermal-pump: 15
conduit: 2
pulse-conduit: 4
liquid-router: 3
liquid-tank: 10
liquid-junction: 2
bridge-conduit: 2
phase-conduit: 5

# Power
power-node: 1
power-node-large: 3
surge-tower: 10
battery: 3
battery-large: 21
combustion-generator: 5
thermal-generator: 8
turbine-generator: 12
differential-generator: 20
rtg-generator: 15
solar-panel: 6
solar-panel-large: 18
thorium-reactor: 25
impact-reactor: 200

# Production
mechanical-drill: 2
pneumatic-drill: 5
laser-drill: 10
blast-drill: 15
water-extractor: 3
cultivator: 7
oil-extractor: 15

# Storage
vault: 20
container: 7
unloader: 3

# Turrets
duo: 3
scatter: 5
scorch: 8
hail: 10
wave: 12
lancer: 15
arc: 18
swarmer: 30
salvo: 24
fuse: 40
ripple: 50
cyclone: 60
spectre: 100
meltdown: 250

# Units
draug-factory: 8
spirit-factory: 12
phantom-factory: 18
command-center: 30
wraith-factory: 15
ghoul-factory: 25
revenant-factory: 40
dagger-factory: 6
crawler-factory: 8
titan-factory: 12
fortress-factory: 18
repair-point: 2

# Upgrade
dart-mech-pad: 15
delta-mech-pad: 30
tau-mech-pad: 40
omega-mech-pad: 150
javelin-ship-pad: 35
trident-ship-pad: 45
glaive-ship-pad: 150