owner:
  inheritance: none
  permission:
    - ALL_PERMISSION
admin:
  inheritance: new_admin
  permission:
    - color
    - difficulty
    - save
    - tempban
new_admin:
  interitance: global
  permission:
    - kill
    - me
    - tpp
default:
  inheritance: guest
  permission:
    - ch
    - event
    - getpos
    - info
    - logout
    - maps
    - motd
    - status
    - suicide
    - time
    - vote
guest:
  inheritance: none
  permission:
    - login
    - register