owner:
  admin: true
  permission:
    - ALL
admin:
  inheritance: newadmin
  admin: true
  permission:
    - color
    - difficulty
    - save
    - tempban
    - save
    - spawn
newadmin:
  inheritance: default
  admin: true
  permission:
    - kill
    - me
    - tpp
    - team
    - tempban
    - tpp
default:
  permission:
    - ch
    - changepw
    - event
    - getpos
    - info
    - login
    - logout
    - maps
    - me
    - motd
    - register
    - status
    - suicide
    - time
    - tp
    - tppos
    - tr
    - vote